[package]
name = "endian_trait_derive"
version = "0.3.0"
authors = [
	"myrrlyn <myrrlyn@outlook.com>",
]
license = "MIT"
description = "A custom derive for the Endian trait"
keywords = [
	"endian",
	"custom-derive",
]
readme = "README.md"
repository = "https://gitlab.com/myrrlyn/endian_trait"
workspace = ".."

[lib]
proc-macro = true

[dependencies]
quote = "0.3"
syn = "0.11"

[dependencies.endian_trait]
path = ".."
version = "0.3"
