[package]
name = "endian_trait_derive"
version = "0.3.2"
authors = [
	"myrrlyn <myrrlyn@outlook.com>",
]
license = "MIT"
description = "A custom derive for the Endian trait"
keywords = [
	"endian",
	"custom-derive",
]
readme = "README.md"
repository = "https://gitlab.com/myrrlyn/endian_trait"
workspace = ".."

[lib]
proc-macro = true

[dependencies]
quote = "0.4"

[dependencies.syn]
version = "0.12"
features = [
	"derive",
]

[dev-dependencies]
endian_trait = "0.3"

[badges.gitlab]
repository = "myrrlyn/endian_trait"
branch = "master"

[badges.maintenance]
status = "passively-maintained"

[badges.travis-ci]
repository = "myrrlyn/endian_trait"
branch = "master"
